### Create Interview with JobApplication Id
POST http://localhost:8080/api/interviews/18
Content-Type: application/json

{
  "interviewDate": "2026-06-10",
  "interviewerName": "John Smith",
  "interviewerType": "Phone Screen",
  "notes": "Talked about Java and Spring Boot"
}

### GET all job applications with interviews
GET http://localhost:8080/api/interviews

### GET most recent interview by Job Application Id
GET http://localhost:8080/api/interviews/getMostRecentInterview/7

### GET all job applications per ApplicationID
GET http://localhost:8080/api/interviews/JopAppInterviews/18

### DELETE all job interviews in applications
DELETE http://localhost:8080/api/interviews

### DELETE all job interviews by Job Application Id
DELETE http://localhost:8080/api/interviews/deleteJobInterviewsByJobAppId/18
