### Send POST request with json body
POST http://localhost:8080/api/applications/createApplication
Content-Type: application/json

{
  "companyName": "Lockheed Martin",
  "jobTitle": "Junior Java Developer",
  "status": "OFFER",
  "dateApplied": "2026-06-06",
  "jobLink": "https://example.com/job",
  "notes": "Applied through Linken"
}

### Update job application by ID
PUT http://localhost:8080/api/applications/1
Content-Type: application/json

{
  "companyName": "Verizon",
  "jobTitle": "Junior Java Developer",
  "status": "APPLIED",
  "dateApplied": "2026-06-06",
  "jobLink": "https://example.com/jobsss",
  "notes": "Applied through Myspace"
}

### GET all job applications
GET http://localhost:8080/api/applications/getAll
Authorization: Basic user 3ca219ef-c1b5-4c7e-af16-cfaba2563e0d

### GET job application by ID
GET http://localhost:8080/api/applications/2

### GET job application by jobTitle
GET http://localhost:8080/api/applications/jobTitle/Java

### GET job application by Status
GET http://localhost:8080/api/applications/status/OFFER

### Delete all job applications
DELETE http://localhost:8080/api/applications

### Delete job applications by id
DELETE http://localhost:8080/api/applications/16


